language: python
sudo: false
cache: pip
stages:
- name: test
- name: deploy to pypi
  if: type = push AND tag =~ ^\d+\.\d+\.\d+
jobs:
  include:
  - env: TOXENV=pypy
    python: pypy
  - env: TOXENV=pypy3
    python: pypy3
  - env: TOXENV=py27
    python: '2.7'
  - env: TOXENV=py34
    python: '3.4'
  - env: TOXENV=py35
    python: '3.5'
  - env: TOXENV=py36
    python: '3.6'
  - env: TOXENV=py37
    dist: xenial
    sudo: required
    python: '3.7'
  - env: TOXENV=flake8
    python: '2.7'
    after_success: skip
  - stage: deploy to PyPI
    install: pip install -U setuptools
    script: skip
    after_success: true
    deploy:
      provider: pypi
      user: agronholm
      password:
        secure: XF58Ejbsl9jeVnyFEg0gtRpBA/wcr0l9HKDq0UmhAKmUiB/42owXkjEbjUL2tAdaiwvaUsujfUeXNnCM3BPFW0l0R4UPs9DW0Xbq55kOqVarQxgaXgo6TdrcrFEPVqN/8++g0+ryU+B/ALeNdiKTFJ9UbremSQsVt26xN3R3WuQ9q8cM+X4Zyc5wrHRzD01nsrYNFKgQeNeSmOWetKQ/rf+J/Qsew0v6mTNSkcCD6Y3J0LBR67V8V/9wmq0wvWHdf6vPdB4AC6LLOkleLq0ALGTmrJkdPvP1/SQMcgosMyqJLoXxfGaS1DcxxcQbRNu9H2LZ6WX3E4tKo9FrRcDt5OTLAxlsyMNth07KRhtIwQ3rLaq0yLMpU7BS4+Mp/mBprxqxDzZQLqiHRV1aWydU4bSehMefkhXw4DqUJoKmw9BcLE4mwJBbHAFUwOP33FAoXXtO985e+BzU57FZj7SrK01wNW5X0FBYHl/FVT2VlI6GJs2IWy1FTRtpX44NQhgBnxEK03HM2qPme6f5h8sgqP59878lkm99tCZVBHAPXQE7uV6XMsm5ZWcT3aGzj73xvVGlFHoUH9Y52vzwxp/xVbwGIzSbFHw6EldjRZefWDYyNYODqLvUHoXPtK2JuC0MfR4O0TvuN4fmCuzTath0TmdsccxuTa9IatKwIoSCRTk=
      distributions: sdist bdist_wheel
      server: https://test.pypi.org/legacy/
      on:
        tags: true
        repo: agronholm/ep2018demo
